#!/bin/bash

# Used to store temporary files
mkdir ./tmp

# Compile assembly to object
i686-elf-as boot.s -o tmp/boot.o

# Compile c to object
i686-elf-gcc -c kernel.c -o tmp/kernel.o -std=gnu99 -ffreestanding -O2 -Wall -Wextra

# Link c with assembly
i686-elf-gcc -T linker.ld -o os_image.bin -ffreestanding -O2 -nostdlib tmp/boot.o tmp/kernel.o -lgcc

# Remove temporary files when we're done using them
rm -rf ./tmp